name: Docker

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  push:
    tags:        
      - v*
env:
  IMAGE_NAME: emailto
  IMAGE_ID: ${{ github.repository_owner }}/emailto
  VERSION: ${{ github.ref }}
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Build image
        run: |
          docker build . --file Dockerfile --tag $IMAGE_NAME --label "runnumber=${GITHUB_RUN_ID}"
          echo $(echo $IMAGE_ID | tr '[A-Z]' '[a-z]') >> $IMAGE_ID
          echo $(echo $VERSION | sed -e 's/^v//') >> $VERSION
          docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
          docker tag $IMAGE_NAME $IMAGE_ID:latest
      - name: Push image to docker.io
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:latest
      - name: Push image to ghcr.io
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
          docker push $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:latest
